-- Legacy `prfobmaster` may exist without an `id` column (CREATE TABLE IF NOT EXISTS in V9 was skipped).
-- Hibernate maps @Id to column `id` — add identity column + primary key when missing.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name = 'prfobmaster'
      AND column_name = 'id'
  ) THEN
    ALTER TABLE prfobmaster
      ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE t.relname = 'prfobmaster'
      AND n.nspname = current_schema()
      AND c.contype = 'p'
  ) THEN
    ALTER TABLE prfobmaster ADD CONSTRAINT prfobmaster_pkey PRIMARY KEY (id);
  END IF;
END $$;
