-- Partial legacy tables may exist without column `id` (CREATE TABLE IF NOT EXISTS was skipped in V12/V13).
-- Hibernate maps @Id → `id` — mirror V10__prfobmaster_add_id.sql.

-- birmaster: optional rename if a legacy PK used a different name
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = current_schema() AND table_name = 'birmaster'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'birmaster' AND column_name = 'id'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'birmaster' AND column_name = 'bir_id'
  ) THEN
    ALTER TABLE birmaster RENAME COLUMN bir_id TO id;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'birmaster' AND column_name = 'id'
  ) THEN
    ALTER TABLE birmaster
      ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE t.relname = 'birmaster'
      AND n.nspname = current_schema()
      AND c.contype = 'p'
  ) THEN
    ALTER TABLE birmaster ADD CONSTRAINT birmaster_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- nonsaleablemaster: optional rename
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = current_schema() AND table_name = 'nonsaleablemaster'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'nonsaleablemaster' AND column_name = 'id'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'nonsaleablemaster' AND column_name = 'nonsaleable_id'
  ) THEN
    ALTER TABLE nonsaleablemaster RENAME COLUMN nonsaleable_id TO id;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'nonsaleablemaster' AND column_name = 'id'
  ) THEN
    ALTER TABLE nonsaleablemaster
      ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE t.relname = 'nonsaleablemaster'
      AND n.nspname = current_schema()
      AND c.contype = 'p'
  ) THEN
    ALTER TABLE nonsaleablemaster ADD CONSTRAINT nonsaleablemaster_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- partnumber_entry (V14)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = current_schema() AND table_name = 'partnumber_entry'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'partnumber_entry' AND column_name = 'id'
  ) THEN
    ALTER TABLE partnumber_entry
      ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = current_schema() AND table_name = 'partnumber_entry'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE t.relname = 'partnumber_entry'
      AND n.nspname = current_schema()
      AND c.contype = 'p'
  ) THEN
    ALTER TABLE partnumber_entry ADD CONSTRAINT partnumber_entry_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- sparepart_master: PK column is spare_id (SparePart entity)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = current_schema() AND table_name = 'sparepart_master'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'sparepart_master' AND column_name = 'spare_id'
  ) THEN
    ALTER TABLE sparepart_master
      ADD COLUMN spare_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = current_schema() AND table_name = 'sparepart_master'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE t.relname = 'sparepart_master'
      AND n.nspname = current_schema()
      AND c.contype = 'p'
  ) THEN
    ALTER TABLE sparepart_master ADD CONSTRAINT sparepart_master_pkey PRIMARY KEY (spare_id);
  END IF;
END $$;
